remix:
  rampage: 
    regex:
      # A-TRP-BrickWall-Low-v4.0.stl
      - '((?P<prefix>[A-Z][a-z]+)-)?(?P<code>[A-Z]+)(-(TRP|RPG))?-(?P<set>[A-Z][a-z]+)(-?(?P<subset>[A-Z][a-z]+))*-v\d.\d.stl' 
  
    config:
      '*': 
        homepage: http://printablescenery.com
        license: commercial 
      'prefix':
        Window: {family: Square} 
        Column: {family: Square, studs: True}
        Floor : {family: Square, studs: False, inputStlOffset: [0,0,-4.2]}
        Wall:   {family: Square, mirrorZ: 7.2}
        _: {family: Square, genus: Tile, studs: False} 
      'set': 
        Wall: &Wall {genus: Wall, studs: True}
        Window: *Wall
        Column: {studs: True} 
      'subset':
        _: {order: '{subset}'}
  
