generate:
  tiles:
    generate:
      x: [1,2,3,4,5,6,7,8]
      y: [1,2,3,4,5,6,7,8]
    condition: '{x} >= {y}'
    config: 
      family: Square
      subfamily: Tile
      set: Blank
      studs: False
      z: 0.25
  walls:
    generate:
      x: [1,2,3,4,5,6,7,8]
    config:
      family: Square
      subfamily: Wall
      set: Blank
      studs: True
      y: 1
      z: 4